name: tripwise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  ionicons: ^0.2.1
<<<<<<< Updated upstream
=======
  awesome_snackbar_content: 0.1.1


>>>>>>> Stashed changes

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  awesome_snackbar_content: ^0.1.3
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  get: ^4.6.6
<<<<<<< Updated upstream
<<<<<<< Updated upstream
=======
  intl: 0.19.0
  video_player: ^2.2.18
  youtube_player_flutter: ^9.0.1
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.2
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
>>>>>>> Stashed changes

  intl: 0.19.0

=======
  intl: 0.19.0
>>>>>>> Stashed changes
  video_player: ^2.2.18


  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/places/
    - assets/icons/
    - assets/images/
    - assets/videos/
